name             'appcatalog_master'
maintainer       'Jer-Ming Chia'
maintainer_email 'jechia@microsoft.com'
license          'All rights reserved'
description      'Additional config for appcatalog master node'
long_description 'Additional config for appcatalog master node'
version          '0.1.0'
